name: False positive
description: Report a false positive here
labels: ["false positive"]
body:
  - type: textarea
    attributes:
      label: Describe the false positive and how to replicate it
      description: |
        Video is always useful. /grim log is required for reporting simulation falses.
        Use /grim verbose and /grim log to get the debug information.
        For non-simulation falses, a minimally reproducable description is best.
      placeholder: |
        Step 1. Do this
        Step 2. Then do this
        Step 3. etc...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Grim version
      description: |
        Provide the git commit or the version in the jar's name.
      placeholder: A example would be b85c2d0 or grim version 2.3.5, etc
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` on your server to check. Provide both the server type (paper, airplane, etc) & the minecraft version.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins
      description: |
        List all plugins running on your server. To list plugins, run `/plugins`.
    validations:
      required: true