name: Feature suggestion
description: Suggest a feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: Describe the feature and why it should be added
    validations:
      required: true